name: API Tests

on:
  push:
  pull_request:
    branches: [dev, main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version}}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version}}
      - name: get chrome
        run: wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb

      - name: install chrome
        run: sudo apt install ./google-chrome-stable_current_amd64.deb

      - name: npm install
        run: npm install
      - name: backend
        run: nohup npm run backend & exit

      - name: gui testing
        run: npm test
