name: test and deploy
# this is a test to see whats what what what
on:
  pull_request:
    branches: [main, dev]

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - run: npm run build --if-present
      - run: nohup npm start &
      - run: npm test

  deploy:
    needs: [tests]
    environment: "Main deploy"

    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd /var/www/Cypress-cucumber
            git pull
            npm install
            npm run build --if-present
            pm2 restart lumia-shop
            pm2 restart reverse-proxy
